// src/pages/LandingPage.jsx
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext.jsx";
import ThemeToggle from "../components/ThemeToggle.jsx";

const EXAMS = [
  { icon: "🎖️", name: "PMA Long Course", category: "Military" },
  { icon: "⚔️", name: "Pakistan Army", category: "Military" },
  { icon: "🚢", name: "Pakistan Navy", category: "Military" },
  { icon: "✈️", name: "Pakistan Air Force", category: "Military" },
  { icon: "🛡️", name: "ASF", category: "Security" },
  { icon: "🕵️", name: "FIA", category: "Security" },
  { icon: "👮", name: "Police", category: "Security" },
  { icon: "📋", name: "FPSC", category: "Civil" },
  { icon: "📝", name: "PPSC", category: "Civil" },
  { icon: "🧾", name: "NTS / GAT", category: "Civil" },
  { icon: "⚡", name: "WAPDA", category: "Engineering" },
  { icon: "🔬", name: "MDCAT", category: "Medical" },
  { icon: "🔧", name: "ECAT", category: "Engineering" },
  { icon: "🎓", name: "University Admission", category: "Academic" },
  { icon: "🪖", name: "ISSB Prep", category: "Military" },
];

const FEATURES = [
  {
    icon: "�",
    title: "Curated Question Bank",
    desc: "Practice using a verified question bank with exam-style MCQs organized by subject, difficulty, and exam type.",
  },
  {
    icon: "⏱️",
    title: "Real Exam Simulator",
    desc: "Practice in a timed environment that mirrors actual exam conditions, complete with countdown timer and auto-submit.",
  },
  {
    icon: "📊",
    title: "Performance Analytics",
    desc: "Detailed score tracking, progress charts, and weak-area identification to focus your study time effectively.",
  },
  {
    icon: "🏆",
    title: "Leaderboard & Streaks",
    desc: "Compete with other students on the national leaderboard. Maintain daily study streaks to unlock achievements.",
  },
  {
    icon: "📅",
    title: "AI Study Plans",
    desc: "Get a personalised daily study plan generated by AI based on your target exam, timeline, and current skill level.",
  },
  {
    icon: "📜",
    title: "Achievement Certificates",
    desc: "Earn and download official-looking certificates when you reach score milestones in any mock test.",
  },
];

export default function LandingPage() {
  const navigate = useNavigate();
  const { isAuthenticated } = useAuth();

  return (
    <div className="min-h-screen bg-slate-950 text-white font-sans">
      {/* Navbar */}
      <nav className="sticky top-0 z-50 bg-slate-950/80 backdrop-blur-xl border-b border-slate-800/60 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <span className="text-2xl">⚡</span>
          <span className="text-xl font-extrabold bg-gradient-to-r from-indigo-400 to-purple-400 bg-clip-text text-transparent">
            SmartPrep AI
          </span>
        </div>
        <div className="flex items-center gap-4">
          <ThemeToggle />
          {isAuthenticated ? (
            <button
              onClick={() => navigate("/dashboard")}
              className="px-5 py-2 text-sm font-bold rounded-xl bg-indigo-600 hover:bg-indigo-700 transition"
            >
              Go to Dashboard →
            </button>
          ) : (
            <>
              <button
                onClick={() => navigate("/login")}
                className="px-5 py-2 text-sm font-semibold text-slate-300 hover:text-white transition"
              >
                Sign In
              </button>
              <button
                onClick={() => navigate("/register")}
                className="px-5 py-2 text-sm font-bold rounded-xl bg-indigo-600 hover:bg-indigo-700 transition"
              >
                Get Started Free
              </button>
            </>
          )}
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative overflow-hidden px-6 pt-24 pb-20 text-center">
        {/* Background glow blobs */}
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-indigo-600/20 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-purple-600/20 rounded-full blur-3xl pointer-events-none" />

        <div className="relative max-w-4xl mx-auto space-y-6">
          <span className="inline-block px-4 py-1.5 text-xs font-bold rounded-full border border-indigo-500/50 bg-indigo-500/10 text-indigo-300 tracking-widest uppercase">
            🇵🇰 Pakistan's #1 Exam Prep Platform
          </span>

          <h1 className="text-5xl md:text-7xl font-black leading-tight">
            Crack Any
            <span className="block bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
              Government Exam
            </span>
          </h1>

          <p className="text-lg text-slate-400 max-w-2xl mx-auto">
            AI-powered mock tests for PMA, PAF, Navy, MDCAT, ECAT, FPSC, PPSC
            and 15+ other top exams. Real exam conditions. Smart analytics.
            Personal study plans.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
            <button
              onClick={() => navigate("/register")}
              className="px-8 py-4 text-base font-bold rounded-2xl bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 shadow-xl shadow-indigo-900/40 transition-all hover:scale-105 active:scale-95"
            >
              🚀 Start Preparing Free
            </button>
            <button
              onClick={() => navigate("/login")}
              className="px-8 py-4 text-base font-bold rounded-2xl border border-slate-700 hover:border-slate-500 bg-slate-900 hover:bg-slate-800 transition-all"
            >
              Sign In to Dashboard
            </button>
          </div>

          {/* Stats Row */}
          <div className="flex justify-center gap-10 pt-10">
            {[
              { num: "15+", label: "Supported Exams" },
              { num: "500+", label: "Practice Questions" },
              { num: "AI", label: "Powered Engine" },
            ].map((stat) => (
              <div key={stat.label} className="text-center">
                <div className="text-3xl font-black text-white">{stat.num}</div>
                <div className="text-xs text-slate-500 mt-1">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Supported Exams Ticker */}
      <section className="py-16 bg-slate-900/40 border-y border-slate-800/50">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-center text-xs font-bold text-slate-500 uppercase tracking-widest mb-8">
            Covering All Major Pakistan Exams
          </h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-3">
            {EXAMS.map((exam) => (
              <div
                key={exam.name}
                className="bg-slate-900 border border-slate-800 rounded-xl p-3 flex items-center gap-2 hover:border-indigo-500/50 hover:bg-slate-800 transition-all cursor-default group"
              >
                <span className="text-xl group-hover:scale-110 transition-transform">
                  {exam.icon}
                </span>
                <div>
                  <div className="text-xs font-bold text-slate-200 leading-tight">
                    {exam.name}
                  </div>
                  <div className="text-[10px] text-slate-500">
                    {exam.category}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-4xl font-black text-white mb-3">
              Everything You Need to
              <span className="text-indigo-400"> Succeed</span>
            </h2>
            <p className="text-slate-400">
              Precision tools built for Pakistan's most competitive examinations
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map((feature) => (
              <div
                key={feature.title}
                className="bg-slate-900 border border-slate-800 hover:border-indigo-500/40 rounded-2xl p-6 transition-all group hover:shadow-xl hover:shadow-indigo-900/20"
              >
                <div className="text-4xl mb-4 group-hover:scale-110 transition-transform inline-block">
                  {feature.icon}
                </div>
                <h3 className="text-lg font-bold text-white mb-2">
                  {feature.title}
                </h3>
                <p className="text-sm text-slate-400 leading-relaxed">
                  {feature.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 px-6 bg-slate-900/40 border-y border-slate-800/50">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl font-black text-white mb-14">How It Works</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                step: "01",
                title: "Create Your Profile",
                desc: "Register and choose your target exam. Set your preparation timeline.",
              },
              {
                step: "02",
                title: "Take Mock Tests",
                desc: "Attempt exam-style MCQs from a curated question bank under real exam conditions with auto-grading.",
              },
              {
                step: "03",
                title: "Track & Improve",
                desc: "Review analytics, follow your AI study plan, and earn achievement badges.",
              },
            ].map((item) => (
              <div key={item.step} className="relative">
                <div className="text-7xl font-black text-slate-800 mb-4">
                  {item.step}
                </div>
                <h3 className="text-xl font-bold text-white mb-2">
                  {item.title}
                </h3>
                <p className="text-sm text-slate-400">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 px-6 text-center">
        <div className="max-w-3xl mx-auto space-y-6">
          <h2 className="text-5xl font-black text-white">
            Your Dream Career
            <span className="block text-transparent bg-gradient-to-r from-indigo-400 to-pink-400 bg-clip-text">
              Starts Today
            </span>
          </h2>
          <p className="text-slate-400">
            Join thousands of students who are preparing smarter with SmartPrep
            AI.
          </p>
          <button
            onClick={() => navigate("/register")}
            className="px-10 py-5 text-lg font-bold rounded-2xl bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 shadow-2xl shadow-indigo-900/50 transition-all hover:scale-105 active:scale-95"
          >
            🎯 Start Your Free Preparation
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-800 py-8 px-6 text-center">
        <div className="flex items-center justify-center gap-2 mb-3">
          <span>⚡</span>
          <span className="font-bold text-slate-300">SmartPrep AI</span>
        </div>
        <p className="text-xs text-slate-600">
          © {new Date().getFullYear()} SmartPrep AI · Built for Pakistan's
          aspirants · All rights reserved
        </p>
      </footer>
    </div>
  );
}
